# code: language=ansible
---
- hosts: "{{ windows_host }}"
  vars:
    ansible_connection: winrm
    ansible_ssh_port: 5986
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
  gather_facts: no

  tasks:
    - name: TBD
